package app.visto.ui

/**
 * Centralized Chinese UI strings for Visto v0.2.
 *
 * Kept as a Kotlin object (rather than `strings.xml`) to keep build and
 * preview cycles fast; we can lift these into resources once we localize
 * beyond zh-CN.
 */
object Strings {
    // App-wide
    const val APP_NAME = "Visto"
    const val LOADING = "加载中…"
    const val BACK = "返回"
    const val DISMISS = "知道了"
    const val NO_SERVER_TITLE = "还没有 WebDAV 服务器"
    const val NO_SERVER_SUBTITLE = "先进入应用没有问题；需要浏览相册时，在设置里添加一个 WebDAV 服务器。"

    // Account screen
    const val ACCOUNT_TITLE = "连接 WebDAV 账号"
    const val ACCOUNT_DISPLAY_NAME = "显示名称"
    const val ACCOUNT_SERVER_URL = "服务器地址 (https://...)"
    const val ACCOUNT_USERNAME = "用户名"
    const val ACCOUNT_PASSWORD = "密码 / 应用令牌"
    const val ACCOUNT_ROOT_PATH = "根路径"
    const val ACCOUNT_TEST_CONNECTION = "测试连接"
    const val ACCOUNT_SAVE_AND_USE = "保存并使用"
    const val ACCOUNT_TESTING = "测试中…"
    const val ACCOUNT_SAVING = "保存中…"
    const val ACCOUNT_CONNECTION_OK = "连接成功"
    const val ACCOUNT_CREDENTIALS_TITLE = "账号凭据"
    const val ACCOUNT_CREDENTIALS_UNAVAILABLE = "无法读取账号凭据"
    const val ACCOUNT_READD_SERVER = "请重新添加服务器。"

    // Account errors
    const val ERR_INVALID_URL = "服务器地址必须以 http:// 或 https:// 开头"
    const val ERR_EMPTY_USERNAME = "用户名不能为空"
    const val ERR_EMPTY_PASSWORD = "密码不能为空"
    const val ERR_AUTH = "认证失败，请检查账号和密码"
    const val ERR_NOT_FOUND = "服务器找不到该路径"
    const val ERR_TIMEOUT = "连接超时，请检查网络"
    const val ERR_NETWORK = "网络错误，请稍后重试"
    const val ERR_SERVER = "服务器错误，请稍后重试"
    const val ERR_INVALID_PATH = "路径不能包含 . 或 .. 段"
    const val ERR_UNEXPECTED = "未知错误"

    // Browser (legacy directory mode)
    const val BROWSER_TITLE = "浏览"
    const val BROWSER_FOLDERS = "文件夹"
    const val BROWSER_MEDIA = "媒体"
    const val BROWSER_BOOKS = "书籍"
    const val BROWSER_EMPTY = "此目录为空"
    const val BROWSER_LOAD_FAILED = "加载失败"
    const val BROWSER_RELOAD = "重新加载"
    const val BROWSER_GO_UP = "返回上一级"
    const val BROWSER_GO_ROOT = "返回根目录"
    const val BROWSER_BOOK_TYPE_TXT = "TXT"
    const val BROWSER_BOOK_TYPE_EPUB = "EPUB"

    // Albums
    const val ALBUMS_TITLE = "相册"
    const val ALBUMS_EMPTY_TITLE = "还没有相册"
    const val ALBUMS_EMPTY_SUBTITLE = "添加一个 WebDAV 路径，开始浏览"
    const val ALBUMS_ADD = "添加相册"
    const val ALBUMS_ADD_DIALOG_TITLE = "添加相册"
    const val ALBUMS_NAME_LABEL = "相册名称"
    const val ALBUMS_PATH_LABEL = "WebDAV 路径"
    const val ALBUMS_PATH_HINT = "例如 /Photos/Family。应用会递归读取该路径下的所有媒体"
    const val ALBUMS_SAVE = "保存"
    const val ALBUMS_CANCEL = "取消"
    const val ALBUMS_BROWSE = "浏览…"
    const val ALBUMS_DELETE = "删除"
    const val ALBUMS_DELETE_CONFIRM_TITLE = "删除相册"
    const val ALBUMS_DELETE_CONFIRM_MESSAGE = "只会从相册列表移除，不会删除 WebDAV 上的文件。"
    const val ALBUMS_ACTIONS_TITLE = "相册操作"
    const val ALBUMS_OPEN = "打开相册"
    const val ALBUMS_COPY_PATH = "复制路径"
    const val ALBUMS_REMOVE_LOCAL = "从 Visto 移除"
    const val ALBUMS_REMOVE_LOCAL_HINT = "只移除本地相册入口，不删除服务器上的照片。"
    const val ALBUMS_ERR_PATH_REQUIRED = "请输入 WebDAV 路径"
    const val ALBUMS_ERR_PATH_MUST_START_WITH_SLASH = "路径必须以 / 开头"
    const val ALBUMS_ERR_DUPLICATE = "已经添加过这个路径了"

    // Album detail
    const val ALBUM_DETAIL_ROOT_SECTION = "根目录"
    const val ALBUM_DETAIL_REFRESH = "刷新"
    const val RETRY = "重试"
    const val ALBUM_DETAIL_LOADING = "正在读取 WebDAV…"
    const val ALBUM_DETAIL_NO_MEDIA = "未找到媒体文件"
    const val ALBUM_VIEW_MODE_FOLDERS = "文件夹"
    const val ALBUM_VIEW_MODE_FLAT = "所有图片"
    const val ALBUM_VIEW_MODE_TOGGLE = "切换查看方式"
    const val ALBUM_FOLDER_EMPTY = "这个文件夹是空的"
    const val ALBUM_NO_COVER = "未找到封面"

    // Folder picker
    const val FOLDER_PICKER_TITLE = "选择 WebDAV 路径"
    const val FOLDER_PICKER_SELECT_CURRENT = "选择当前目录"
    const val FOLDER_PICKER_EMPTY = "这个目录下没有子文件夹"
    const val FOLDER_PICKER_UP = "上一级"

    fun albumDetailProgress(visited: Int, failed: Int): String {
        val base = "已扫描 $visited 个目录"
        return if (failed == 0) base else "$base，$failed 个失败"
    }

    fun albumDetailSectionCount(count: Int): String = "$count 个文件"

    // Bookshelf and reader
    const val BOOKSHELF_TITLE = "书架"
    const val BOOKSHELF_CONTINUE_READING = "继续阅读"
    const val BOOKSHELF_REMOVE = "从书架移除"
    const val BOOKSHELF_REMOVE_CONFIRM_MESSAGE = "从书架移除不会删除 WebDAV 上的文件"
    const val BOOKSHELF_REMOVE_CONFIRM = "移除"
    const val BOOKSHELF_EMPTY = "浏览中打开 TXT 文件后自动加入书架"
    const val BOOKSHELF_VIEW_MODE = "视图"
    const val BOOKSHELF_GRID_VIEW = "书架"
    const val BOOKSHELF_LIST_VIEW = "列表"
    const val BOOKSHELF_JUST_NOW = "刚刚"
    const val BOOKSHELF_LONG_AGO = "很久以前"

    const val READER_CHAPTERS = "目录"
    const val READER_CHAPTER_SEARCH = "搜索章节"
    const val READER_CHAPTER_SEARCH_PLACEHOLDER = "输入标题或章节号"
    const val READER_CHAPTER_SEARCH_EMPTY = "没有匹配的章节"
    const val READER_CURRENT_CHAPTER = "当前章节"
    const val READER_LOAD_FAILED = "加载失败"
    const val READER_EMPTY = "暂无可阅读内容"
    const val READER_SETTINGS = "阅读设置"
    const val READER_SET_DEFAULT_SETTINGS = "设为默认阅读设置"
    const val READER_FONT = "字体"
    const val READER_FONT_SYSTEM = "默认"
    const val READER_FONT_SANS = "黑体"
    const val READER_FONT_SERIF = "宋体"
    const val READER_FONT_IMPORT = "导入 .ttf / .otf 字体"
    const val READER_FONT_IMPORT_FAILED = "字体导入失败"
    const val READER_FONT_IMPORT_UNSUPPORTED = "请选择 .ttf 或 .otf 字体文件"
    const val READER_FONT_SIZE = "字号"
    const val READER_LINE_SPACING = "行距"
    const val READER_LINE_SPACING_COMPACT = "紧凑"
    const val READER_LINE_SPACING_STANDARD = "标准"
    const val READER_LINE_SPACING_RELAXED = "宽松"
    const val READER_THEME = "主题"
    const val READER_THEME_LIGHT = "白天"
    const val READER_THEME_DARK = "夜间"
    const val READER_THEME_CREAM = "护眼"
    const val READER_TEXT_COLOR = "文字颜色"
    const val READER_BACKGROUND_STYLE = "阅读背景"
    const val READER_PREVIEW = "预览"
    const val READER_PREVIEW_TEXT = "这是 Visto 阅读器的文字预览。调整字号、行距和主题后，会实时应用到这里。"
    const val READER_PREVIOUS_PAGE = "上一页"
    const val READER_NEXT_PAGE = "下一页"
    const val READER_EPUB_UNSUPPORTED = "EPUB 阅读暂未支持"

    fun bookshelfChapterNumber(index: Int): String = "第${(index + 1).coerceAtLeast(1)}章"
    fun bookshelfProgressPercent(percent: Int): String = " · 已读$percent%"
    fun bookshelfLastRead(relative: String): String = "最后阅读 $relative"
    fun bookshelfMinutesAgo(minutes: Long): String = "${minutes}分钟前"
    fun bookshelfHoursAgo(hours: Long): String = "${hours}小时前"
    fun bookshelfDaysAgo(days: Long): String = "${days}天前"
    fun readerCustomFont(name: String): String = "自定义：$name"
    fun readerFontSize(sp: Int): String = "$READER_FONT_SIZE ${sp}sp"
    fun readerPageStatus(chapterTitle: String, page: Int, totalPages: Int): String =
        "$chapterTitle $page/$totalPages 页"
    fun readerChapterNumber(index: Int): String = "第 ${index + 1} 章"

    // Settings
    const val SETTINGS_TITLE = "设置"
    const val SETTINGS_ACCOUNT = "账号"
    const val SETTINGS_ADD_SERVER = "添加 WebDAV 服务器"
    const val SETTINGS_SET_ACTIVE_SERVER = "设为当前"
    const val SETTINGS_ACTIVE_SERVER = "当前服务器"
    const val SETTINGS_NO_SERVER = "还没有添加服务器"
    const val SETTINGS_ROOT_LABEL = "根路径："
    const val SETTINGS_APPEARANCE = "外观"
    const val SETTINGS_THEME_SYSTEM = "跟随系统"
    const val SETTINGS_THEME_LIGHT = "浅色模式"
    const val SETTINGS_THEME_DARK = "深色模式"
    const val SETTINGS_BROWSE_MODE = "浏览方式"
    const val SETTINGS_BROWSE_MODE_ALBUMS = "相册（默认）"
    const val SETTINGS_BROWSE_MODE_DIR = "按目录浏览（旧版）"
    const val SETTINGS_AUTO_LOAD_ORIGINAL = "自动加载原图"
    const val SETTINGS_AUTO_LOAD_ORIGINAL_DESC = "关闭后，点开图片会先确认，避免误下载大图。"
    const val SETTINGS_BLUR_THUMBNAILS = "模糊缩略图"
    const val SETTINGS_BLUR_THUMBNAILS_DESC = "开启后，相册和浏览列表里的缩略图会模糊；点进最终图片查看页后正常显示。"
    const val SETTINGS_GRID_DENSITY = "网格密度"
    const val SETTINGS_GRID_DENSITY_DESC = "影响相册详情和浏览页的缩略图大小。"
    const val SETTINGS_CLEAR_THUMBNAILS = "清除本地缩略图"
    const val SETTINGS_CLEAR_BOOK_CACHE = "清理书籍缓存"
    const val SETTINGS_CLEARING = "清理中…"
    const val SETTINGS_CACHE_CLEARED = "本地缩略图已清除，未触碰 WebDAV 上的文件。"
    const val SETTINGS_BOOK_CACHE_CLEARED = "书籍缓存已清理"
    const val SETTINGS_CACHE_LIMIT_LABEL = "缩略图缓存上限"
    const val SETTINGS_CACHE_LIMIT_HINT = "由 LRU 逐渐淘汰旧缓存；需要立即释放可以点下面“清除本地缩略图”。"
    const val SETTINGS_ABOUT_TITLE = "关于"
    const val SETTINGS_CHECK_UPDATE = "检查更新"
    const val SETTINGS_CHECKING_UPDATE = "检查中…"
    const val SETTINGS_LATEST_VERSION_ALREADY = "已是最新版本"
    const val SETTINGS_DOWNLOAD_AND_INSTALL = "下载并安装"
    const val SETTINGS_DOWNLOADING = "下载中…"
    const val SETTINGS_INSTALL_NOW = "立即安装"
    const val SETTINGS_NEW_VERSION = "发现新版本"
    const val SETTINGS_RELEASE_NOTES = "更新内容"
    const val SETTINGS_OPEN_RELEASE_PAGE = "打开发布页"
    const val SETTINGS_UPDATE_SAVED_TO_DOWNLOADS = "APK 已下载到系统下载目录"
    const val SETTINGS_CHECK_UPDATE_FAILED = "检查更新失败"
    const val SETTINGS_DOWNLOAD_UPDATE_FAILED = "下载更新失败"
    const val SETTINGS_INSTALLER_FAILED = "启动安装器失败"
    const val SETTINGS_WEBDAV_CONNECTION_FAILED = "WebDAV 连接失败"
    const val SETTINGS_CONNECTION_TEST = "连接测试"
    const val SETTINGS_IMAGE = "图片"
    const val SETTINGS_READING = "阅读"
    const val SETTINGS_READER_DEFAULTS = "默认阅读设置"
    const val SETTINGS_READER_DEFAULTS_NOTE = "在书籍内保存默认设置后会更新这里；已打开过的书籍保留各自设置。"
    const val SETTINGS_READER_BOOK_CACHE_NOTE = "只清理本地下载的书籍文本缓存，不会删除 WebDAV 上的文件。"

    const val VIEWER_LOAD_ORIGINAL = "加载原图"
    const val VIEWER_ORIGINAL_HINT = "原图可能较大，加载前会通过 WebDAV 下载。"

    fun thumbnailsOnDisk(formatted: String): String = "本地缩略图占用：$formatted"
}
